.pragma library

// The UI's concise action names; scripts/doctor.py checks its Hyprland keys.
var shortcuts = [
    { key: "Ctrl+Shift+?", title: "Search this field guide", group: "Desktop", detail: "Ctrl+Shift+/ on the US keyboard" },
    { key: "Super+F2", title: "Open the field guide", group: "Desktop", detail: "Accessible alternate binding" },
    { key: "Tap Super", title: "Application launcher", group: "Desktop", detail: "Search installed apps on the focused display" },
    { key: "Super+1…6", title: "Named workspaces", group: "Workspace", detail: "Terminal · Web · Code · Sim · Work · Misc" },
    { key: "Super+Shift+1…6", title: "Move window to workspace", group: "Workspace", detail: "Preserves the focused window" },
    { key: "Super+Tab", title: "Workspace switcher", group: "Workspace", detail: "Shift reverses direction" },
    { key: "Super+A", title: "Workspace overview", group: "Workspace", detail: "Drag windows between workspaces" },
    { key: "Alt+Tab", title: "Application switcher", group: "Window", detail: "Shift reverses direction" },
    { key: "Alt+`", title: "Same-application switcher", group: "Window", detail: "Cycle instances of the focused app" },
    { key: "Super+arrows", title: "Focus nearby window", group: "Window", detail: "Directional focus" },
    { key: "Super+Shift+↑/↓", title: "Move window between displays", group: "Window", detail: "Main / ScreenPad" },
    { key: "Super+C", title: "Close focused window", group: "Window", detail: "Closes an app window; tmux work remains" },
    { key: "Super+V", title: "Toggle floating", group: "Window", detail: "Tiling or floating window" },
    { key: "Super+F", title: "Toggle fullscreen", group: "Window", detail: "Focused window" },
    { key: "Super+mouse drag", title: "Move or resize window", group: "Window", detail: "Left drag moves; right drag resizes" },
    { key: "Super+Return / Super+Q / Alt+Return", title: "Focus terminal", group: "Launch", detail: "Launch BAY when none is open" },
    { key: "Shift+launch key", title: "Force new app window", group: "Launch", detail: "Otherwise focus an existing instance" },
    { key: "Alt+W", title: "Focus Chrome", group: "Launch", detail: "NVIDIA browser, or open it" },
    { key: "Alt+F", title: "Focus files", group: "Launch", detail: "Nautilus, or open it" },
    { key: "Super+P", title: "Calculator", group: "Launch", detail: "Shift opens another window" },
    { key: "Super+W", title: "Wallpaper and theme", group: "Desktop", detail: "Separate image for each display" },
    { key: "Super+Shift+V", title: "Clipboard vault", group: "Desktop", detail: "Saved text, images and files" },
    { key: "Super+Shift+M", title: "System monitor", group: "Desktop", detail: "Live hardware and process details" },
    { key: "Super+E", title: "Wrayth deck", group: "Desktop", detail: "Kitty-powered control deck" },
    { key: "Super+L", title: "Lock session", group: "Desktop", detail: "Manual lock" },
    { key: "Super+Ctrl+P", title: "Power menu", group: "Desktop", detail: "Session and power actions" },
    { key: "Ctrl+Space", title: "Spotify play or pause", group: "Music", detail: "Global playback control" },
    { key: "Ctrl+← / →", title: "Previous or next track", group: "Music", detail: "Global playback control" },
    { key: "Ctrl+↑ / ↓", title: "Music volume", group: "Music", detail: "Global playback control" },
    { key: "Print", title: "Area screenshot", group: "Capture", detail: "Save and copy to clipboard" },
    { key: "Shift+Print", title: "Display screenshot", group: "Capture", detail: "Focused output" },
    { key: "Alt+Print", title: "Window screenshot", group: "Capture", detail: "Focused window" },
    { key: "Ctrl+Print", title: "Whole-desktop screenshot", group: "Capture", detail: "Both displays" },
    { key: "Super+Print", title: "Record a display", group: "Capture", detail: "Press again to stop" },
    { key: "Super+Shift+Print", title: "Record an area", group: "Capture", detail: "Press again to stop" },
    { key: "Super+Shift+D", title: "OCR selection", group: "Capture", detail: "Read text from selected area to clipboard" },
    { key: "Ctrl+Shift+N", title: "New persistent terminal", group: "Alacritty", detail: "Opens another BAY workbench" },
    { key: "Super+' / Ctrl+Shift+Return", title: "New tmux window", group: "Alacritty", detail: "Persistent tab in the current BAY" },
    { key: "Super+[ / ]", title: "Previous or next tmux window", group: "Alacritty", detail: "Switch tabs within BAY" },
    { key: "Ctrl+Shift+L", title: "Change pane layout", group: "Alacritty", detail: "Cycle tmux split layouts" },
    { key: "Ctrl+Shift+M", title: "Zoom pane", group: "Alacritty", detail: "Toggle single-pane view" },
    { key: "Ctrl+Shift+E", title: "Window picker", group: "Alacritty", detail: "Browse tmux windows" },
    { key: "Ctrl+Shift+↑", title: "Enter scrollback", group: "Alacritty", detail: "Works inside Codex and Claude Code" },
    { key: "Ctrl+Shift+F / B", title: "Find terminal text", group: "Alacritty", detail: "Alacritty forward / backward search" },
    { key: "Ctrl+Shift+C / V", title: "Copy or paste", group: "Alacritty", detail: "System clipboard" },
    { key: "Ctrl+Shift+Y", title: "Open btop", group: "Alacritty", detail: "Dedicated system monitor window" },
    { key: "Ctrl+Shift+G", title: "Open nvtop", group: "Alacritty", detail: "Dedicated GPU monitor window" },
    { key: "` then | / -", title: "Split current pane", group: "tmux", detail: "Vertical divider / horizontal divider" },
    { key: "` then g", title: "Find a project", group: "tmux", detail: "Fuzzy project picker opens a persistent window" },
    { key: "` then S", title: "Synchronize panes", group: "tmux", detail: "Toggle broadcast; status shows SYNC while armed" },
    { key: "` then s / w", title: "Sessions or windows", group: "tmux", detail: "Browse tmux trees" },
    { key: "` then Ctrl+S / Ctrl+R", title: "Save or restore layout", group: "tmux", detail: "tmux-resurrect; not live process hibernation" },
    { key: "` then r", title: "Reload tmux", group: "tmux", detail: "Read updated config" },
    { key: "Super+F3…F12", title: "ZenBook function layer", group: "ZenBook", detail: "Quick controls, mic, power, touchpad, keyboard, displays, camera, capture and robotics" },
    { key: "Fan / Swap / ScreenPad buttons", title: "Dedicated ASUS controls", group: "ZenBook", detail: "Model-specific hardware keys" }
];
