import QtQuick
import QtQuick.Controls
import QtQuick.Layouts
import Quickshell
NoesisDialog {
 id:root
 property string kind:"resource"
 property string parentId:""
 property string vaultScope:""
 property bool submitting:false
 property string submittedOperation:""
 property var promptingAttempt:({})
 property var questionEvidence:[]
 property bool transfer:false
 property bool saved:false
 property bool initialized:false
 property string mediumPreference:""
 readonly property string draftKey:vaultScope+":form:create:"+kind+":"+parentId+":"+String(transfer)+":"+mediumPreference+(promptingAttempt.id?":"+promptingAttempt.id:"")
 property string learningDemo:""
 function beginConvolution(){begin("concept","",false,"convolution-example");if(!name.text.trim())name.text="Convolution";prefill("Example starting point · supplied by Noesis\nThis is an editable learning prompt, not completed learner work.\n\nMy question\nHow can the same local rule smooth a signal or detect a change?\n\nWhat remains uncertain\nPadding, reversal, stride and the limits of this small example.\n");}
 function prefill(value){if(!details.text.trim())details.text=value;}
 function stashDraft(){if(!initialized||saved)return;let next=Object.assign({},NoesisController.drafts);next[draftKey]=JSON.stringify({name:name.text,details:details.text,source:source.text,repository:repository.text,entry:entry.text,revision:revision.text,medium:medium.currentIndex});NoesisController.drafts=next;NoesisController.savePreferences();}
 function discardDraft(){let next=Object.assign({},NoesisController.drafts);delete next[draftKey];NoesisController.drafts=next;NoesisController.savePreferences();}
 onClosed:if(!saved)stashDraft()
 Timer {id:formSave;interval:500;onTriggered:root.stashDraft()}
 Connections {target:NoesisController;function onFlushRequested(){formSave.stop();root.stashDraft();}}
 signal created(var record)
 modal:true
 width:560
 height:Math.min((kind==="concept"?480:700)*NoesisStyle.interfaceScale,(parent?.height||800)-32)
 title:kind==="concept"?"Start a concept investigation":transfer?"Try a changed problem":kind==="unit"?"Add a lesson or chapter":kind==="question"?"Preserve a question":kind==="task"?"Add a problem":kind==="experiment"?"Create an experiment":kind==="artifact"?"Connect data, a figure or code":kind==="path"?"Create a learning path":kind==="project"?"Connect an implementation":kind==="capability"?"Define a capability":"Save a resource"
 closePolicy:Popup.CloseOnEscape
 function begin(recordKind,parent,isTransfer,preferredMedium,attempt){initialized=false;learningDemo=preferredMedium==="convolution-example"?"convolution-1d":"";promptingAttempt=attempt||({});questionEvidence=promptingAttempt.id?[{vault_id:NoesisController.currentContext.vault_id,record_id:promptingAttempt.id}]:[];saved=false;mediumPreference=preferredMedium||"";transfer=!!isTransfer;vaultScope=NoesisController.activeVault;kind=recordKind;parentId=parent||"";name.text="";details.text="";source.text="";repository.text="";entry.text="";revision.text="";medium.currentIndex=Math.max(0,medium.model.indexOf(preferredMedium||""));submitting=false;initialized=true;try{let draft=JSON.parse(NoesisController.drafts[draftKey]||"null");if(draft){name.text=draft.name||"";details.text=draft.details||"";source.text=draft.source||"";repository.text=draft.repository||"";entry.text=draft.entry||"";revision.text=draft.revision||"";medium.currentIndex=Math.max(0,Math.min(medium.count-1,draft.medium||0));}}catch(error){}if(promptingAttempt.id&&!details.text.trim())details.text="## What blocked this attempt?\n\n\n## Current explanation\n\n\n## Smallest changed case to investigate\n\n";open();name.forceActiveFocus();}
 background:Rectangle {color:NoesisStyle.canvas;radius:NoesisStyle.radius;}
 contentItem:ScrollView {id:form;clip:true;contentWidth:availableWidth;ScrollBar.horizontal.policy:ScrollBar.AlwaysOff
 ColumnLayout {width:form.availableWidth;spacing:NoesisStyle.lg
  Text {visible:!!root.promptingAttempt.id;Layout.fillWidth:true;text:"Connected to the saved "+(root.promptingAttempt.outcome||"unknown")+" attempt. Its assistance and original reasoning stay in history; this question does not turn the failure into success.";textFormat:Text.PlainText;wrapMode:Text.Wrap;color:NoesisStyle.secondary;font.family:NoesisStyle.uiFont;font.pixelSize:NoesisStyle.label}
  Text {renderType:Text.NativeRendering;font.hintingPreference:Font.PreferFullHinting;textFormat:Text.PlainText;text:"Title";color:NoesisStyle.ink;font.family:NoesisStyle.uiFont;font.pixelSize:NoesisStyle.label}
  NoesisField {id:name;objectName:"record-title";onTextChanged:if(root.initialized&&root.visible)formSave.restart();Accessible.name:"Learning object title";placeholderText:root.kind==="unit"?"Lesson or chapter title":"Title";Layout.fillWidth:true}
  Text {renderType:Text.NativeRendering;font.hintingPreference:Font.PreferFullHinting;textFormat:Text.PlainText;visible:root.kind==="resource"||root.kind==="unit";text:root.kind==="unit"?"Lesson kind":"Source kind";color:NoesisStyle.ink;font.family:NoesisStyle.uiFont;font.pixelSize:NoesisStyle.label}
  NoesisSelect {id:medium;onCurrentIndexChanged:if(root.initialized&&root.visible)formSave.restart();Accessible.name:"Source or lesson kind";visible:root.kind==="resource"||root.kind==="unit";Layout.fillWidth:true;model:root.kind==="unit"?["lecture","reading","chapter","section","video","assignment","module"]:["paper","book","course","video","playlist","article","docs","dataset","other"]}
  Text {renderType:Text.NativeRendering;font.hintingPreference:Font.PreferFullHinting;textFormat:Text.PlainText;visible:["resource","unit","artifact","task"].includes(root.kind);text:"Source or file · optional";color:NoesisStyle.ink;font.family:NoesisStyle.uiFont;font.pixelSize:NoesisStyle.label}
  NoesisField {id:source;objectName:"record-source";onTextChanged:if(root.initialized&&root.visible)formSave.restart();Accessible.name:"Source URL or local file";visible:["resource","unit","artifact","task"].includes(root.kind);placeholderText:root.kind==="artifact"?"Existing file path or source URL":"Source URL or local PDF path · optional";Layout.fillWidth:true}
  Text {renderType:Text.NativeRendering;font.hintingPreference:Font.PreferFullHinting;textFormat:Text.PlainText;visible:root.kind==="project";text:"Git repository · optional";color:NoesisStyle.ink;font.family:NoesisStyle.uiFont;font.pixelSize:NoesisStyle.label}
  NoesisField {id:repository;objectName:"record-repository";onTextChanged:if(root.initialized&&root.visible)formSave.restart();visible:root.kind==="project";Layout.fillWidth:true;placeholderText:"Existing Git repository path · optional";Accessible.name:"Implementation repository"}
  Text {visible:root.kind==="project";text:"Code file within repository · optional";color:NoesisStyle.ink;font.family:NoesisStyle.uiFont;font.pixelSize:NoesisStyle.label;Layout.fillWidth:true}
  NoesisField {id:entry;objectName:"record-code-file";visible:root.kind==="project";Layout.fillWidth:true;Accessible.name:"Code file within repository";placeholderText:"For example, src/shortest_paths.py";onTextChanged:if(root.initialized&&root.visible)formSave.restart()}
  Text {renderType:Text.NativeRendering;font.hintingPreference:Font.PreferFullHinting;textFormat:Text.PlainText;visible:root.kind==="artifact";text:"Artifact revision · optional";color:NoesisStyle.ink;font.family:NoesisStyle.uiFont;font.pixelSize:NoesisStyle.label}
  NoesisField {id:revision;objectName:"record-revision";onTextChanged:if(root.initialized&&root.visible)formSave.restart();Accessible.name:"Artifact revision";visible:root.kind==="artifact";Layout.fillWidth:true;placeholderText:"Code commit, dataset version or configuration · optional"}
  Text {renderType:Text.NativeRendering;font.hintingPreference:Font.PreferFullHinting;textFormat:Text.PlainText;text:root.kind==="experiment"?"Prediction":root.kind==="task"?"Statement and criterion":root.kind==="capability"?"Assessment criteria":"Purpose and context";color:NoesisStyle.ink;font.family:NoesisStyle.uiFont;font.pixelSize:NoesisStyle.label}
  ScrollView {id:detailsScroll;Layout.fillWidth:true;Layout.preferredHeight:Math.max(140,NoesisStyle.control*3);clip:true;NoesisEditor {id:details;objectName:"record-purpose";onTextChanged:if(root.initialized&&root.visible)formSave.restart();width:detailsScroll.availableWidth;Accessible.name:"Learning object details";placeholderText:root.kind==="capability"?"Assessment criteria · one per line":root.kind==="task"?"Problem statement and criterion. Keep reference solutions separate.":root.kind==="question"?"What is unclear? Preserve your current explanation.":root.kind==="experiment"?"Your prediction, assumptions and what you want to measure…":"Why this matters now · optional"}}
  Text {renderType:Text.NativeRendering;font.hintingPreference:Font.PreferFullHinting;text:root.parentId?"Connected to your current context. Identity and history are automatic.":"You can add lessons, problems and evidence as you work.";color:NoesisStyle.secondary;font.family:NoesisStyle.uiFont;font.pixelSize:NoesisStyle.label;wrapMode:Text.Wrap;Layout.fillWidth:true}
  Text {renderType:Text.NativeRendering;font.hintingPreference:Font.PreferFullHinting;Layout.fillWidth:true;visible:NoesisController.error!=="";textFormat:Text.PlainText;text:NoesisController.error;wrapMode:Text.Wrap;color:NoesisStyle.error;font.family:NoesisStyle.uiFont;font.pixelSize:NoesisStyle.label;Accessible.name:"Save error"}
 }}
 footer:Flow {spacing:NoesisStyle.sm
   NoesisButton {text:"Keep draft";onClicked:root.close()}
   NoesisButton {id:saveButton;text:"Save";hint:"Ctrl+Enter";primary:true;enabled:name.text.trim()!==""&&!NoesisController.working&&!NoesisController.uncertainReceipt&&!NoesisController.exitRequested&&root.vaultScope===NoesisController.activeVault;onClicked:{let fields={};if(root.learningDemo)fields.learning_demo=root.learningDemo;if(["resource","unit","artifact","task"].includes(root.kind)){if(root.kind==="resource")fields.source_kind=medium.currentText;let link=source.text.trim();if(/^https?:\/\//.test(link)){fields.source=link;fields.external_aliases=["url:"+link];if(/^https?:\/\/(dx\.)?doi\.org\//i.test(link)){fields.doi=link.replace(/^https?:\/\/(dx\.)?doi\.org\//i,"");fields.external_aliases.push("doi:"+fields.doi.toLowerCase());}}else if(/^10\.\d{4,9}\//.test(link)){fields.doi=link;fields.source="https://doi.org/"+link;fields.external_aliases=["doi:"+link.toLowerCase()];}else if(/^arxiv:/i.test(link)){fields.arxiv=link.slice(6);fields.source="https://arxiv.org/abs/"+fields.arxiv;}else if(link)fields.local_file=link;}if(root.kind==="question"){fields.investigation={depth:"normal"};if(root.questionEvidence.length)fields.evidence_refs=root.questionEvidence;}if(root.kind==="task"){fields.source_kind="problem-statement";if(root.transfer)fields.practice_mode="transfer";}if(root.kind==="unit")fields.unit_kind=medium.currentText;if(root.kind==="artifact"&&revision.text.trim())fields.revision=revision.text.trim();if(root.kind==="capability")fields.criteria=details.text.split(/\r?\n/).map(line=>line.trim()).filter(line=>line!=="");if(root.kind==="experiment")fields.hypothesis=details.text;if(root.kind==="project"&&repository.text.trim()){fields.repository=repository.text.trim();if(entry.text.trim())fields.code_entrypoint=entry.text.trim();}let args=["record",root.kind,name.text,"--body",root.kind==="task"?"## Problem statement\n\n"+details.text:details.text,"--data",JSON.stringify(fields)];if(root.parentId)args.push("--parent-id",root.parentId,"--relation",root.transfer?"references":root.kind==="task"?"assigns":root.kind==="capability"?"pursues":root.kind==="question"?"investigates":"contains");NoesisController.run(args);root.submittedOperation=NoesisController.operationId;root.submitting=root.submittedOperation!=="";}}
 }
 Shortcut {sequence:"Ctrl+Return";enabled:root.visible;onActivated:if(saveButton.enabled)saveButton.clicked()}
 Connections {target:NoesisController;function onFinished(ok){if(root.submitting&&root.submittedOperation===NoesisController.operationId){root.submitting=false;if(ok){root.saved=true;root.discardDraft();root.created(NoesisController.operationResult);root.close();}}}}
}
